pipeline:
  test_docker_build:
    image: plugins/docker
    when:
      event: pull_request
  build_and_push_docker_image:
    image: plugins/docker
    repo: geezyx/ruby-nodejs
    auto_tag: true
    secrets: [ docker_username, docker_password ]
    when:
      event: push
      branch: master
